# goal definition
Header goal_header
geometry_msgs/PoseStamped pose
bool scan
---
# result definition
Header result_header
tiago_iaslab_simulation/circle[] obstacles
---
# feedback
Header feedback_header
uint8 current_status
